services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=posts_db
      - POSTGRES_HOST_AUTH_METHOD=trust
  backend:
    build: .
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/posts_db
      PORT: 5000